-- Apply to product_db. Unquoted PostgreSQL identifiers are lowercase.
BEGIN;

CREATE TABLE product (
    pid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR,
    image VARCHAR,
    price NUMERIC,
    status BOOLEAN,
    date_added DATE,
    last_updated DATE
);

-- One inventory row per product. Referenced products cannot be deleted.
CREATE TABLE inventory (
    pid INTEGER PRIMARY KEY REFERENCES product (pid),
    qty INTEGER,
    backorder BOOLEAN
);

COMMIT;
