spring.application.name=payment-service
spring.cloud.config.name=payment-service

# Continue starting while Config Server is not yet available.
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

#---
# Enable the database profile once a datasource has been configured.
spring.config.activate.on-profile=!database
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

# Active Profile & App Settings
spring.profiles.active=dev
server.port=8085

# Spring Cloud Config (Optional/Fail-safe)
spring.cloud.config.enabled=false

# H2 Datasource Settings
spring.datasource.url=jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true